config/routes.rb
Rails.application.routes.draw do
 
  
  devise_for :authors
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: "home#index"
   scope module: 'authors' do
      resources :posts do
        resources :elements
      end
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/elements_controller.rb
module Authors

class ElementsController < AuthorsController
  before_action :set_element, only: [:show, :edit, :update, :destroy]

  # GET /elements
  def index
    @elements = Element.all
  end

  # GET /elements/1
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements
  def create
    @element = Element.new(element_params)

    if @element.save
      redirect_to @element, notice: 'Element was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /elements/1
  def update
    if @element.update(element_params)
      redirect_to @element, notice: 'Element was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /elements/1
  def destroy
    @element.destroy
    redirect_to elements_url, notice: 'Element was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def element_params
      params.require(:element).permit(:element_type, :content, :post_id, :position)
    end
end

end

app/controllers/authors/posts_controller.rb
module Authors


class PostsController < AuthorsController
  before_action :set_post, only: [ :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = current_author.posts
  end

  # GET /posts/new
  def new
    @post = current_author.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_author.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!
  
  layout 'authors'
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control"%>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<%= link_to 'Back', posts_path, class: 'btn btn-secondary mb-3' %>

<div class="row">
	
	<div class="col-md-3">
		
	  <div class="card">
		  
		  <div class="card-body">
			  
			  <h4 class="card-title">Editing Post</h4>
			  <%= render 'form', post: @post %>
		  </div>
	  </div>
	  
	 </div>
 </div>

app/views/authors/posts/index.html.erb
<h4 class="d-flex justify-content-between mb-4">
	<span>Posts</span>
	<%= link_to 'New Post', new_post_path , class: 'btn btn-primary'%>
</h4>


<% @posts.each do |post| %>

	<%=link_to edit_post_path(post), class: 'text-decoration-none' do%>
		<div class="card mb-3">
			<div class="card-body">
				<h5 class='card-title mb-1 text-dark'><%=post.title%></h5>
				<p class='text-secondary mb-0'><%=post.description%></p>
			</div>
		</div>
	<%end%>

<%end%>

app/views/authors/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/authors/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @post.published %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @post.published_at %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-ligth">
	  <div class="container">
	  	  	<p class="notice"><%= notice %></p>
	  		<p class="alert"><%= alert %></p>
	      	<%= yield %>
	  </div>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-ligth">
	  <div class="container">
	  	  	<p class="notice"><%= notice %></p>
	  		<p class="alert"><%= alert %></p>
	      	<%= yield %>
	  </div>
  </body>
</html>